### ISSUE TITLE
CRITICAL  | raft.Server: Name cannot be blank

### ISSUE THREAD

**Issue by borillo** [microbox/etcd#2]
When i try to run:
docker run --rm -it -p 4001:4001 -p 7001:7001 -v /var/etcd/:/data microbox/etcd:latest

Environment:
Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Docker version:
Docker version 1.5.0, build a8a31ef

**Comment by apennebaker-ni** [comment]
+1

**Comment by microbox** [comment]
solved this issue by using busybox as the base image.

**Comment by stongo** [comment]
I know this is closed, but the current image on registry still has this issue. Solution is to specify `--name=foo` flag as a container argument

**Comment by Hokutosei** [comment]
Greetings,

anyone fixed this? it is still occurring on me

```
-> % docker run --rm --name=test -p 4001:4001 -p 7001:7001 -v /var/etcd/:/data microbox/etcd:latest
[etcd] Sep  3 02:06:05.341 CRITICAL  | raft.Server: Name cannot be blank
```

**Comment by brid** [comment]
Same here. I don't know how naming a container would fix a problem internal to the running container?

**Comment by Hokutosei** [comment]
@microbox could you please check this?

**Comment by computerlyrik** [comment]
@Hokutosei  @brid Solution here: https://github.com/microbox/etcd/issues/5
@stongo said it right - just misunderstanding of _placing_ the name parameter
