### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by bavodaniels** [microbox/etcd#4]
hey when i do the following command

docker run --rm -it -p 4001:4001 -p 7001:7001 -v /var/etcd/:/data microbox/etcd:latest --help

i get 

Code: System error

Message: [/usr/bin/tar -cf /mnt/Data/Docker/tmp/99ac3785e4b51645ea700cb6a7fbc1c5f22dd0c5febfdc7892136ed786ea78db752561213/_tmp.tar -C /mnt/Data/Docker/devicemapper/mnt/99ac3785e4b51645ea700cb6a7fbc1c5f22dd0c5febfdc7892136ed786ea78db/rootfs/tmp .] failed: /usr/bin/tar: /mnt/Data/Docker/devicemapper/mnt/99ac3785e4b51645ea700cb6a7fbc1c5f22dd0c5febfdc7892136ed786ea78db/rootfs/tmp: Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
: exit status 2

any ideas to fix this?

im running docker 1.6.0
fedora linux as host OS

**Comment by microbox** [comment]
This is because this image does not include any system tool. The new image solved this problem which contains busybox as base image.
